#' Biological Value Index grapher
#' 
#' @description Creates a graph to graphicaly represent the score matrix of the Biological Value Index.
#' 
#' @param bvi_scores An object of class data.frame generated generated by bvi()
#' 
#' @seealso bvi
#' 
#' @author Villasenor-Derbez, J.C.
#' 
#' @export
#' 
bvi_plot=function(bvi_scores){
  
}